"""Add automation core phase 1

Revision ID: 7537de7834ab
Revises: 0003_kanban_producao_simple
Create Date: 2026-05-20 09:49:56.035370
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7537de7834ab'
down_revision = '0003_kanban_producao_simple'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_id', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('approval_type', sa.String(length=100), nullable=False),
    sa.Column('requested_by_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approver_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approver_role', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_by_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('callback_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_approvals_approval_id'), 'automation_approvals', ['approval_id'], unique=True)
    op.create_index(op.f('ix_automation_approvals_correlation_id'), 'automation_approvals', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_automation_approvals_created_at'), 'automation_approvals', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_approvals_request_id'), 'automation_approvals', ['request_id'], unique=False)
    op.create_table('automation_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('workflow', sa.String(length=200), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_audit_logs_correlation_id'), 'automation_audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_automation_audit_logs_created_at'), 'automation_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_audit_logs_request_id'), 'automation_audit_logs', ['request_id'], unique=False)
    op.create_table('automation_dead_letters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('workflow', sa.String(length=200), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('failed_node', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('redacted_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_dead_letters_correlation_id'), 'automation_dead_letters', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_automation_dead_letters_created_at'), 'automation_dead_letters', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_dead_letters_idempotency_key'), 'automation_dead_letters', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_automation_dead_letters_request_id'), 'automation_dead_letters', ['request_id'], unique=False)
    op.create_table('automation_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('workflow', sa.String(length=200), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('failed_node', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('redacted_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_errors_correlation_id'), 'automation_errors', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_automation_errors_created_at'), 'automation_errors', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_errors_request_id'), 'automation_errors', ['request_id'], unique=False)
    op.create_table('automation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('workflow', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_events_correlation_id'), 'automation_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_automation_events_created_at'), 'automation_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_events_request_id'), 'automation_events', ['request_id'], unique=False)
    op.create_table('ia_workflow_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.String(length=100), nullable=False),
    sa.Column('workflow_name', sa.String(length=200), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_execution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('errors_last_24h', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ia_workflow_status_workflow_id'), 'ia_workflow_status', ['workflow_id'], unique=True)
    op.drop_index('ix_kanban_activity_logs_board_id', table_name='kanban_activity_logs')
    op.drop_index('ix_kanban_activity_logs_card_id', table_name='kanban_activity_logs')
    op.drop_index('ix_kanban_activity_logs_user_id', table_name='kanban_activity_logs')
    op.drop_index('ix_kanban_attachments_card_id', table_name='kanban_attachments')
    op.drop_index('ix_kanban_attachments_file_id', table_name='kanban_attachments')
    op.drop_constraint('uq_kanban_attachments_card_file', 'kanban_attachments', type_='unique')
    op.create_index('uq_kanban_attachments_card_file', 'kanban_attachments', ['card_id', 'file_id'], unique=True)
    op.drop_index('ix_kanban_board_permissions_board_id', table_name='kanban_board_permissions')
    op.drop_index('ix_kanban_board_permissions_role_id', table_name='kanban_board_permissions')
    op.drop_index('ix_kanban_board_permissions_user_id', table_name='kanban_board_permissions')
    op.drop_index('ix_kanban_card_assignees_card_id', table_name='kanban_card_assignees')
    op.drop_index('ix_kanban_card_assignees_user_id', table_name='kanban_card_assignees')
    op.drop_constraint('uq_kanban_card_assignees_card_user', 'kanban_card_assignees', type_='unique')
    op.create_index('uq_kanban_card_assignees_card_user', 'kanban_card_assignees', ['card_id', 'user_id'], unique=True)
    op.drop_index('ix_kanban_card_types_board_id', table_name='kanban_card_types')
    op.drop_index('ix_kanban_card_types_key', table_name='kanban_card_types')
    op.drop_constraint('uq_kanban_columns_board_key', 'kanban_columns', type_='unique')
    op.create_index('uq_kanban_columns_board_key', 'kanban_columns', ['board_id', 'key'], unique=True)
    op.drop_constraint('uq_kanban_columns_board_order', 'kanban_columns', type_='unique')
    op.create_index('uq_kanban_columns_board_order', 'kanban_columns', ['board_id', 'order_index'], unique=True)
    op.add_column('notifications', sa.Column('correlation_id', sa.String(length=100), nullable=True))
    op.add_column('notifications', sa.Column('request_id', sa.String(length=100), nullable=True))
    op.add_column('notifications', sa.Column('target_department', sa.String(length=120), nullable=True))
    op.add_column('notifications', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('notifications', sa.Column('channel', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_notifications_correlation_id'), 'notifications', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_notifications_request_id'), 'notifications', ['request_id'], unique=False)
    op.create_index(op.f('ix_production_order_checklist_items_production_order_id'), 'production_order_checklist_items', ['production_order_id'], unique=False)
    op.drop_constraint('uq_production_orders_numero_op', 'production_orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_production_orders_numero_op', 'production_orders', ['numero_op'])
    op.drop_index(op.f('ix_production_order_checklist_items_production_order_id'), table_name='production_order_checklist_items')
    op.drop_index(op.f('ix_notifications_request_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_correlation_id'), table_name='notifications')
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('notifications', 'payload')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'channel')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'target_department')
    op.drop_column('notifications', 'request_id')
    op.drop_column('notifications', 'correlation_id')
    op.drop_index('uq_kanban_columns_board_order', table_name='kanban_columns')
    op.create_unique_constraint('uq_kanban_columns_board_order', 'kanban_columns', ['board_id', 'order_index'])
    op.drop_index('uq_kanban_columns_board_key', table_name='kanban_columns')
    op.create_unique_constraint('uq_kanban_columns_board_key', 'kanban_columns', ['board_id', 'key'])
    op.create_index('ix_kanban_card_types_key', 'kanban_card_types', ['key'], unique=False)
    op.create_index('ix_kanban_card_types_board_id', 'kanban_card_types', ['board_id'], unique=False)
    op.drop_index('uq_kanban_card_assignees_card_user', table_name='kanban_card_assignees')
    op.create_unique_constraint('uq_kanban_card_assignees_card_user', 'kanban_card_assignees', ['card_id', 'user_id'])
    op.create_index('ix_kanban_card_assignees_user_id', 'kanban_card_assignees', ['user_id'], unique=False)
    op.create_index('ix_kanban_card_assignees_card_id', 'kanban_card_assignees', ['card_id'], unique=False)
    op.create_index('ix_kanban_board_permissions_user_id', 'kanban_board_permissions', ['user_id'], unique=False)
    op.create_index('ix_kanban_board_permissions_role_id', 'kanban_board_permissions', ['role_id'], unique=False)
    op.create_index('ix_kanban_board_permissions_board_id', 'kanban_board_permissions', ['board_id'], unique=False)
    op.drop_index('uq_kanban_attachments_card_file', table_name='kanban_attachments')
    op.create_unique_constraint('uq_kanban_attachments_card_file', 'kanban_attachments', ['card_id', 'file_id'])
    op.create_index('ix_kanban_attachments_file_id', 'kanban_attachments', ['file_id'], unique=False)
    op.create_index('ix_kanban_attachments_card_id', 'kanban_attachments', ['card_id'], unique=False)
    op.create_index('ix_kanban_activity_logs_user_id', 'kanban_activity_logs', ['user_id'], unique=False)
    op.create_index('ix_kanban_activity_logs_card_id', 'kanban_activity_logs', ['card_id'], unique=False)
    op.create_index('ix_kanban_activity_logs_board_id', 'kanban_activity_logs', ['board_id'], unique=False)
    op.drop_index(op.f('ix_ia_workflow_status_workflow_id'), table_name='ia_workflow_status')
    op.drop_table('ia_workflow_status')
    op.drop_index(op.f('ix_automation_events_request_id'), table_name='automation_events')
    op.drop_index(op.f('ix_automation_events_created_at'), table_name='automation_events')
    op.drop_index(op.f('ix_automation_events_correlation_id'), table_name='automation_events')
    op.drop_table('automation_events')
    op.drop_index(op.f('ix_automation_errors_request_id'), table_name='automation_errors')
    op.drop_index(op.f('ix_automation_errors_created_at'), table_name='automation_errors')
    op.drop_index(op.f('ix_automation_errors_correlation_id'), table_name='automation_errors')
    op.drop_table('automation_errors')
    op.drop_index(op.f('ix_automation_dead_letters_request_id'), table_name='automation_dead_letters')
    op.drop_index(op.f('ix_automation_dead_letters_idempotency_key'), table_name='automation_dead_letters')
    op.drop_index(op.f('ix_automation_dead_letters_created_at'), table_name='automation_dead_letters')
    op.drop_index(op.f('ix_automation_dead_letters_correlation_id'), table_name='automation_dead_letters')
    op.drop_table('automation_dead_letters')
    op.drop_index(op.f('ix_automation_audit_logs_request_id'), table_name='automation_audit_logs')
    op.drop_index(op.f('ix_automation_audit_logs_created_at'), table_name='automation_audit_logs')
    op.drop_index(op.f('ix_automation_audit_logs_correlation_id'), table_name='automation_audit_logs')
    op.drop_table('automation_audit_logs')
    op.drop_index(op.f('ix_automation_approvals_request_id'), table_name='automation_approvals')
    op.drop_index(op.f('ix_automation_approvals_created_at'), table_name='automation_approvals')
    op.drop_index(op.f('ix_automation_approvals_correlation_id'), table_name='automation_approvals')
    op.drop_index(op.f('ix_automation_approvals_approval_id'), table_name='automation_approvals')
    op.drop_table('automation_approvals')
    # ### end Alembic commands ###
