import { DEFAULT_BOARD_CONFIG } from "./config";
import type { KanbanBoardTemplate, KanbanHubContext } from "./types";

export const FALLBACK_CONTEXTS: KanbanHubContext[] = [
  {
    key: "quadros",
    name: "Quadros",
    description: "Todos os quadros do Kanban Engine.",
    kind: "system",
    boardType: null,
    moduleContext: null,
    route: null,
    icon: "KanbanSquare",
    order: 10,
    visible: true,
    isSystem: true,
    requiredPermission: "kanban.board.view",
    deletedAt: null,
  },
  {
    key: "producao",
    name: "Producao",
    description: "OPs simples e checklist editavel.",
    kind: "specialized",
    boardType: "production",
    moduleContext: "producao",
    route: "/kanban/producao",
    icon: "Factory",
    order: 20,
    visible: true,
    isSystem: true,
    requiredPermission: "kanban_producao.view",
    deletedAt: null,
  },
  {
    key: "projetos",
    name: "Projetos",
    description: "Quadros de projetos e tarefas.",
    kind: "generic",
    boardType: "projects",
    moduleContext: "projetos",
    route: null,
    icon: "FolderKanban",
    order: 30,
    visible: true,
    isSystem: true,
    requiredPermission: "kanban.board.view",
    deletedAt: null,
  },
  {
    key: "ti_operacional",
    name: "TI / Operacional",
    description: "Quadros de TI, suporte e fluxos operacionais.",
    kind: "generic",
    boardType: "operational",
    moduleContext: "ti",
    route: null,
    icon: "MonitorCog",
    order: 40,
    visible: true,
    isSystem: true,
    requiredPermission: "kanban.board.view",
    deletedAt: null,
  },
  {
    key: "personalizados",
    name: "Personalizados",
    description: "Fluxos customizados por equipe.",
    kind: "generic",
    boardType: "custom",
    moduleContext: "outro",
    route: null,
    icon: "SlidersHorizontal",
    order: 50,
    visible: true,
    isSystem: true,
    requiredPermission: "kanban.board.view",
    deletedAt: null,
  },
  {
    key: "tv_foco",
    name: "TV/Foco",
    description: "Visualizacao ampla dos quadros permitidos.",
    kind: "specialized",
    boardType: null,
    moduleContext: null,
    route: "/kanban/tv",
    icon: "Tv",
    order: 60,
    visible: true,
    isSystem: true,
    requiredPermission: "kanban.board.view",
    deletedAt: null,
  },
];

export const FALLBACK_TEMPLATES: KanbanBoardTemplate[] = [
  {
    key: "basico",
    name: "Basico",
    description: "Fluxo simples para qualquer equipe.",
    boardType: "custom",
    moduleContext: "outro",
    icon: "KanbanSquare",
    color: "#38d3ee",
    isSystem: true,
    isActive: true,
    order: 10,
    columns: [
      { name: "A fazer", key: "a_fazer", order: 10 },
      { name: "Em andamento", key: "em_andamento", order: 20 },
      { name: "Revisao", key: "revisao", order: 30 },
      { name: "Concluido", key: "concluido", order: 40, isDone: true },
    ],
    config: DEFAULT_BOARD_CONFIG,
    deletedAt: null,
  },
  {
    key: "projetos",
    name: "Projetos",
    description: "Template para projetos e tarefas.",
    boardType: "projects",
    moduleContext: "projetos",
    icon: "FolderKanban",
    color: "#38d3ee",
    isSystem: true,
    isActive: true,
    order: 20,
    columns: [
      { name: "Backlog", key: "backlog", order: 10 },
      { name: "Planejamento", key: "planejamento", order: 20 },
      { name: "Em execucao", key: "em_execucao", order: 30 },
      { name: "Validacao", key: "validacao", order: 40 },
      { name: "Entregue", key: "entregue", order: 50, isDone: true },
    ],
    config: {
      ...DEFAULT_BOARD_CONFIG,
      terminology: {
        ...DEFAULT_BOARD_CONFIG.terminology,
        itemSingular: "Tarefa",
        itemPlural: "Tarefas",
        newItemLabel: "Nova tarefa",
        editItemLabel: "Editar tarefa",
      },
    },
    deletedAt: null,
  },
  {
    key: "ti_chamados",
    name: "TI / Chamados",
    description: "Template para chamados internos de TI.",
    boardType: "operational",
    moduleContext: "ti",
    icon: "MonitorCog",
    color: "#38d3ee",
    isSystem: true,
    isActive: true,
    order: 30,
    columns: [
      { name: "Aberto", key: "aberto", order: 10 },
      { name: "Em atendimento", key: "em_atendimento", order: 20 },
      { name: "Aguardando usuario", key: "aguardando_usuario", order: 30 },
      { name: "Resolvido", key: "resolvido", order: 40 },
      { name: "Fechado", key: "fechado", order: 50, isDone: true },
    ],
    config: {
      ...DEFAULT_BOARD_CONFIG,
      terminology: {
        ...DEFAULT_BOARD_CONFIG.terminology,
        itemSingular: "Chamado",
        itemPlural: "Chamados",
        newItemLabel: "Novo chamado",
        editItemLabel: "Editar chamado",
      },
      card: {
        fields: [
          {
            key: "solicitante",
            label: "Solicitante",
            type: "text",
            required: false,
            showInCard: true,
            showInDrawer: true,
            showInTv: true,
            showInFilters: true,
            order: 10,
          },
        ],
      },
    },
    deletedAt: null,
  },
];

export function canSeeContext(context: KanbanHubContext, permissions: string[]) {
  if (!context.visible || context.deletedAt) return false;
  if (!context.requiredPermission) return true;
  return permissions.includes(context.requiredPermission) || permissions.includes("kanban.admin") || permissions.includes("admin.permissions.manage");
}
